service: pdf-service

custom:
  bucket: pdf-service-upload 
  stage: dev

provider:
  name: aws
  runtime: nodejs6.10
  stage: ${self:custom.stage}
  region: eu-west-1
  # apiKeys:
  #   - ${self:custom.stage}-chromeless-session-key

plugins:
  - serverless-plugin-typescript