service: pdf-service

custom:
  bucket: pdf-service-upload
  webpack: ./config/webpack.config.js  
  webpackIncludeModules: true


provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1

functions:
  generate:
    handler: api/pdf.generate
    events:
      - http:
          path: generate/{$id}
          method: get
          cors: true

plugins:
  - serverless-webpack
  - serverless-offline


# package:
#   exclude:
#     - node_modules/**/*
#   include:
#     handler.ts