service: pdf-service

custom:
  bucket: pdf-invoice-generator

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-west-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
      Resource: "arn:aws:s3:::${self:custom.bucket}/*"

functions:
  hello:
    handler: handler.hello
    environment:
      BUCKET: ${self:custom.bucket}
    events:
      - http:
          path: generate
          method: post
          cors: true

plugins:
  - serverless-plugin-typescript
  - serverless-offline

package:
  exclude:
    - node_modules/**/*
  include:
    handler.ts