service: pdf-service

custom:
  bucket: pdf-service-upload
  webpack: ./config/webpack.config.js  
  webpackIncludeModules: true


provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  # region: us-west-1

  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
      Resource: "arn:aws:s3:::${self:custom.bucket}/*"

functions:
  generate:
    handler: api/pdf.generate
    events:
      - http:
          path: generate/{$id}
          method: get
          cors: true
          authorizer: aws_iam

plugins:
  - serverless-webpack
  - serverless-offline


# package:
#   exclude:
#     - node_modules/**/*
#   include:
#     handler.ts